### ISSUE TITLE
Integration into custom build image fails

### ISSUE THREAD

**Issue by canaindica** [vasvir/openwrt-packages#6]
After having built the apt-cacher-ng Package in the build root, the integration into a custom image fails. Because at the time of packet integration into an image a free uid/gid cannot be resolved by the build system itself. Most packages which use uid/gid in their Makefile specifiy the USERID-option with a fixed number. E.g. makefiles of syncthing or openssh-server.
This issue can be solved by adding an UID/GID right after the user-/groupname in the USERID-Field of the makefile.

**Comment by vasvir** [comment]
So your pull request #4 assigns uid:gid = 319:319 to apt-cacher-ng matching the gentoo conventions.

The question is what are the preferred conventions of the openwrt project?

I did a bit of research in the issue:

There is this discussion 7 years ago: https://openwrt-devel.openwrt.narkive.com/sazTnNOJ/patch-rfc-dnsmasq-run-as-dedicated-uid-gid In this thread someone mention is that the preferred convention of the openwrt is what debian does but debian auto-assigns number in 100-500 range. Here is the documentation: https://www.debian.org/doc/debian-policy/ch-opersys.html#users-and-groups

Gentoo is more clear on that with a formal registry https://wiki.gentoo.org/wiki/UID_GID_Assignment_Table and statically assigned ids.

So what can we possibly do here? There are no clear guidelines.

Personally I think it is a bug / limitation of the image building tooling. I think this is an issue openwrt and related tooling need to solve it in a higher level than of this package.

Having said that, I am going to accept this patch because it is something vs nothing of the current state. The risk of uid:gid clash is pretty limited IMHO.

Please by all means do drop me  a note if something changes in the openwrt land in the future.
